services:
  app:
    container_name: FAT_project_app
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/code
    ports:
      - "9000:8000"
    restart: always
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: FAT_project_postgres
    environment:
      POSTGRES_DB: FAT_db
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - 5431:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
